Import('env', 'arch', 'cereal', 'messaging', 'common', 'visionipc', 'is_jetson')

src = ['loggerd.cc', 'logger.cc']
libs = ['zmq', 'capnp', 'kj', 'z',
  'avformat', 'avcodec', 'swscale', 'avutil',
  'yuv', 'bz2', common, cereal, messaging, visionipc]

if arch == "aarch64" and not is_jetson:
  src += ['encoder.c', 'raw_logger.cc']
  libs += ['OmxVenc', 'OmxCore', 'cutils']
elif arch == "larch64":
  src += ['encoder.c', 'raw_logger.cc']
  libs += ['OmxVenc', 'OmxCore', 'pthread']
else:
  libs += ['pthread']

env.Program(src, LIBS=libs)
